version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment: 
            FLASK_ENV: development
    mongo:
        image: "mongo"
        environment:
            USERNAME: root
            PASSWORD: password
        volumes: 
            - ./mongo-volume:/data/db